<a href="https://colab.research.google.com/github/TheJavier37/Algebra-Lineal/blob/main/TareaMatrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Definir dos matrices A y B de 3x3
A = np.array([[2, 4, 6],
              [1, 3, 5],
              [0, -1, 2]])

B = np.array([[3, 2, 1],
              [4, 0, -2],
              [1, 3, 5]])

print("Matriz A:\n", A)
print("\nMatriz B:\n", B)

# ------------------------------
# Suma de matrices
# ------------------------------
suma = A + B
print("\n Suma (A + B):\n", suma)
print("\n C[0,0] es igual a: ", A[0,0]+B[0,0])

# ------------------------------
#  Resta de matrices
# ------------------------------
resta = A - B
print("\n Resta (A - B):\n", resta)
print("\n C[2,1] es igual a: ", A[2,1]-B[2,1])

# ------------------------------
# Multiplicación por un escalar
# ------------------------------
escalar = 2
producto_escalar = escalar * A
print(f"\n Multiplicación por escalar ({escalar} * A):\n", producto_escalar)
print("\n A[2,1] es igual a: ", 2 * A[2,1])

# ------------------------------
#  Multiplicación matricial
# ------------------------------
producto = np.dot(A, B)   # o A @ B
print("\n Producto matricial (A * B):\n", producto)
print("\n C[2,2] es igual a: ", A[2,0]*B[0,2]+A[2,1]*B[1,2]+A[2,2]*B[2,2])

# ------------------------------
# Matriz transpuesta
# ------------------------------
# transpuesta = A.T
# print("\n Transpuesta de A (Aᵀ):\n", transpuesta)

Matriz A:
 [[ 2  4  6]
 [ 1  3  5]
 [ 0 -1  2]]

Matriz B:
 [[ 3  2  1]
 [ 4  0 -2]
 [ 1  3  5]]

 Suma (A + B):
 [[5 6 7]
 [5 3 3]
 [1 2 7]]

 C[0,0] es igual a:  5

 Resta (A - B):
 [[-1  2  5]
 [-3  3  7]
 [-1 -4 -3]]

 C[2,1] es igual a:  -4

 Multiplicación por escalar (2 * A):
 [[ 4  8 12]
 [ 2  6 10]
 [ 0 -2  4]]

 A[2,1] es igual a:  -2

 Producto matricial (A * B):
 [[28 22 24]
 [20 17 20]
 [-2  6 12]]

 C[2,2] es igual a:  12


In [ ]:
from datetime import date

nombre = "Javier Guarnizo"
fecha_actual = date.today()
carrera = "Ingenieria en Ciencias de la computación"

print("Nombre:", nombre)
print("Fecha actual:", fecha_actual)
print("Carrera:", carrera)

Nombre: Javier Guarnizo
Fecha actual: 2025-10-21
Carrera: Ingenieria en Ciencias de la computación
